// Sample experts and products.
// Used two ways:
//  1. `npm run db:seed` loads them into your Neon database.
//  2. If no database is connected yet, the site shows this same
//     data in "demo mode" so the pages are never blank.

export const SAMPLE_EXPERTS = [
  {
    slug: "priya-sharma",
    name: "Dr. Priya Sharma",
    specialty: "Clinical Nutritionist",
    photo: "",
    bio: "Dr. Priya Sharma has spent 14 years helping people rebuild their health through evidence-based nutrition. She specialises in metabolic health, PCOS and sustainable weight management, and believes lasting change comes from small, consistent habits — not crash diets. Every consultation ends with a written, practical plan you can start the same day.",
    credentials: ["PhD, Clinical Nutrition (AIIMS)", "Registered Dietitian (IDA)", "14+ years in practice"],
    rating: 4.9,
    reviewCount: 214,
    fee: 999,
    calLink: "",
    featured: true,
  },
  {
    slug: "arjun-mehta",
    name: "Dr. Arjun Mehta",
    specialty: "Ayurveda Physician",
    photo: "",
    bio: "A third-generation Ayurvedic physician, Dr. Mehta blends classical Ayurveda with modern diagnostics. His practice focuses on digestion, stress and lifestyle disorders. He is known for explaining exactly why a protocol is prescribed — and for recommending only what is genuinely needed.",
    credentials: ["BAMS, MD (Ayurveda)", "Member, National Ayurveda Board", "12+ years in practice"],
    rating: 4.8,
    reviewCount: 186,
    fee: 799,
    calLink: "",
    featured: true,
  },
  {
    slug: "kavita-rao",
    name: "Kavita Rao",
    specialty: "Yoga & Breathwork Therapist",
    photo: "",
    bio: "Kavita is a certified yoga therapist who works with clients recovering from back pain, anxiety and burnout. Her sessions pair therapeutic movement with breathwork you can practise anywhere. Expect a calm, judgement-free space and a plan matched to your body, not a template.",
    credentials: ["C-IAYT Certified Yoga Therapist", "RYT-500", "9+ years teaching"],
    rating: 5.0,
    reviewCount: 158,
    fee: 599,
    calLink: "",
    featured: true,
  },
  {
    slug: "neha-kulkarni",
    name: "Dr. Neha Kulkarni",
    specialty: "Dermatologist — Skin & Hair",
    photo: "",
    bio: "Dr. Kulkarni is a consultant dermatologist focused on skin barrier health, adult acne and hair thinning. She takes a minimal, ingredient-first approach: fewer products, chosen well. Consultations include a full routine review so you stop spending on what doesn't work.",
    credentials: ["MBBS, MD (Dermatology)", "Fellow, Indian Association of Dermatologists", "10+ years in practice"],
    rating: 4.8,
    reviewCount: 141,
    fee: 899,
    calLink: "",
    featured: false,
  },
  {
    slug: "rohan-iyer",
    name: "Rohan Iyer",
    specialty: "Sleep & Stress Coach",
    photo: "",
    bio: "Rohan helps busy professionals fix their sleep without medication. A certified sleep science coach, he combines CBT-i techniques with realistic routines for Indian work schedules. Most clients see measurable improvement within three weeks.",
    credentials: ["Certified Sleep Science Coach", "CBT-i Practitioner", "7+ years coaching"],
    rating: 4.7,
    reviewCount: 96,
    fee: 699,
    calLink: "",
    featured: false,
  },
  {
    slug: "vikram-singh",
    name: "Vikram Singh",
    specialty: "Certified Fitness Trainer",
    photo: "",
    bio: "Vikram designs strength and conditioning programmes for beginners and busy professionals. His approach pairs progressive, joint-friendly training with realistic weekly targets — no crash routines, no gym-bro extremes. Every plan comes with video form guides and a fortnightly check-in to keep you on track.",
    credentials: ["ACE Certified Personal Trainer", "Sports Nutrition Specialist (Level 2)", "8+ years coaching"],
    rating: 4.8,
    reviewCount: 112,
    fee: 499,
    calLink: "",
    featured: false,
  },
  {
    slug: "meera-nair",
    name: "Dr. Meera Nair",
    specialty: "Women's Health Specialist",
    photo: "",
    bio: "Dr. Nair supports women through hormonal transitions — PCOS, fertility planning, perimenopause — with a warm, thorough consulting style. She reviews your labs, history and lifestyle together, and coordinates with our nutrition team where helpful.",
    credentials: ["MBBS, DGO", "Diploma in Reproductive Medicine", "11+ years in practice"],
    rating: 4.9,
    reviewCount: 127,
    fee: 899,
    calLink: "",
    featured: false,
  },
];

export const SAMPLE_PRODUCTS = [
  {
    slug: "ashwagandha-ksm66",
    sku: "VW-ASH-60",
    name: "Ashwagandha KSM-66 Capsules",
    description:
      "Clinically studied KSM-66 ashwagandha root extract, 600 mg per serving, to support stress resilience, sleep quality and energy. Each batch is third-party tested for purity and heavy metals.\n\n60 vegetarian capsules — a 30-day supply. Take two capsules with dinner, or as advised by your consultant.",
    price: 899,
    images: [],
    stock: 42,
    category: "Supplements",
    consultRecommended: true,
    featured: true,
  },
  {
    slug: "triphala-tablets",
    sku: "VW-TRI-90",
    name: "Triphala Digestive Tablets",
    description:
      "The classical three-fruit Ayurvedic formulation — amalaki, bibhitaki and haritaki — for gentle daily digestive support and regularity. Made from organically grown fruit, lab-tested for purity.\n\n90 tablets — a 45-day supply. Take two tablets before bed with warm water.",
    price: 449,
    images: [],
    stock: 68,
    category: "Ayurveda",
    consultRecommended: false,
    featured: true,
  },
  {
    slug: "omega3-fish-oil",
    sku: "VW-OMG-60",
    name: "Omega-3 Triple Strength Fish Oil",
    description:
      "High-potency omega-3 with 1,100 mg EPA+DHA per serving for heart, joint and brain health. Molecularly distilled, IFOS-certified, with no fishy aftertaste.\n\n60 softgels — a 30-day supply. Take two softgels with your largest meal.",
    price: 1249,
    images: [],
    stock: 35,
    category: "Supplements",
    consultRecommended: false,
    featured: true,
  },
  {
    slug: "vitamin-d3-k2",
    sku: "VW-D3K2-60",
    name: "Vitamin D3 + K2 Drops",
    description:
      "5,000 IU vitamin D3 paired with K2 (MK-7) for absorption and bone health — the deficiency most commonly flagged in Indian blood work. Sunflower-oil base, one drop a day.\n\n30 ml bottle — approximately a 10-month supply at one drop daily.",
    price: 699,
    images: [],
    stock: 51,
    category: "Supplements",
    consultRecommended: true,
    featured: true,
  },
  {
    slug: "night-calm-tea",
    sku: "VW-TEA-40",
    name: "Night Calm Herbal Tea",
    description:
      "A caffeine-free evening blend of chamomile, ashwagandha, brahmi and rose petals, developed with our sleep coaches. Steep for five minutes, forty minutes before bed.\n\n40 whole-leaf pyramid bags. No added flavours or sweeteners.",
    price: 549,
    images: [],
    stock: 84,
    category: "Teas & Tonics",
    consultRecommended: false,
    featured: false,
  },
  {
    slug: "magnesium-glycinate",
    sku: "VW-MAG-90",
    name: "Magnesium Glycinate Tablets",
    description:
      "Highly absorbable chelated magnesium for muscle recovery, sleep and nervous-system support — gentle on the stomach, unlike oxide forms. 400 mg elemental magnesium per serving.\n\n90 tablets — a 30-day supply. Take three tablets in the evening.",
    price: 799,
    images: [],
    stock: 12,
    category: "Supplements",
    consultRecommended: false,
    featured: false,
  },
  {
    slug: "barrier-repair-serum",
    sku: "VW-SKN-30",
    name: "Barrier Repair Ceramide Serum",
    description:
      "A dermatologist-formulated serum with 5 ceramides, niacinamide and hyaluronic acid to restore a damaged skin barrier. Fragrance-free, non-comedogenic, suitable for sensitive skin.\n\n30 ml airless pump. Apply two pumps to damp skin, morning and night.",
    price: 1399,
    images: [],
    stock: 27,
    category: "Skin & Hair",
    consultRecommended: true,
    featured: false,
  },
  {
    slug: "hair-density-tonic",
    sku: "VW-HAIR-100",
    name: "Hair Density Scalp Tonic",
    description:
      "A leave-in scalp tonic with 3% redensyl, rosemary extract and biotin to support hair density and reduce fall. Lightweight, non-greasy, safe for daily use.\n\n100 ml spray bottle. Apply to scalp nightly and massage in — do not rinse.",
    price: 1099,
    images: [],
    stock: 4,
    category: "Skin & Hair",
    consultRecommended: true,
    featured: false,
  },
];

// Which experts recommend which products (by slug) — used by the seed.
export const SAMPLE_RECOMMENDATIONS: Record<string, string[]> = {
  "priya-sharma": ["omega3-fish-oil", "vitamin-d3-k2", "magnesium-glycinate"],
  "arjun-mehta": ["triphala-tablets", "ashwagandha-ksm66", "night-calm-tea"],
  "kavita-rao": ["magnesium-glycinate", "night-calm-tea"],
  "neha-kulkarni": ["barrier-repair-serum", "hair-density-tonic"],
  "rohan-iyer": ["ashwagandha-ksm66", "night-calm-tea", "magnesium-glycinate"],
  "vikram-singh": ["omega3-fish-oil", "magnesium-glycinate"],
  "meera-nair": ["vitamin-d3-k2", "omega3-fish-oil"],
};
